table Dim_Product
	lineageTag: 550e8400-e29b-41d4-a716-446655440021

	partition Dim_Product = m
		mode: import
		source =
			```
			let
			    Source = Csv.Document(File.Contents("data/Dim_Product.csv"),[Delimiter=",", Columns=1, Encoding=65001, QuoteStyle=QuoteStyle.None]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Changed = Table.TransformColumnTypes(Promoted,{{"ProductID", type text}})
			in
			    Changed
			```

	column ProductID
		dataType: string
		isKey
		isHidden
		sourceColumn: ProductID
		summarizeBy: none
		lineageTag: 550e8400-e29b-41d4-a716-446655440022

	column 'Product Name'
		dataType: string
		sourceColumn: ProductID
		summarizeBy: none
		lineageTag: 550e8400-e29b-41d4-a716-446655440023
